### ISSUE TITLE
[BUG]: items other than transform sent in an envelope request cause an error

### ISSUE THREAD

**Issue by kenkku** [wix/sentry-testkit#89]
**Describe the bug**
Some requests generated by Sentry fail in transformTransaction because they are missing the `contexts` property. It appears that it's trying to use the transformTransaction function for session data.

```
    TypeError: Cannot read property 'trace' of undefined

      at transformTransaction (../node_modules/sentry-testkit/dist/index.js:42:28)
      at ../node_modules/sentry-testkit/dist/index.js:74:28
      at ../node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
          at Array.map (<anonymous>)
      at Object.emit (../node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
      at Page.emit (../node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
      at ../node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:143:100
      at ../node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
          at Array.map (<anonymous>)
      at Object.emit (../node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
```

Here is an example of the request to the envelope enpoint

```
   {"sent_at":"2021-08-17T14:27:12.489Z","sdk":{"name":"sentry.javascript.react","version":"6.11.0"}}
    {"type":"session"}
    {"sid":"<removed>","init":false,"started":"2021-08-17T14:27:11.361Z","timestamp":"2021-08-17T14:27:12.489Z","status":"ok","errors":1,"attrs":{"release":"<removed>","environment":"<removed>","user_agent":"<removed>"}}
```

**To Reproduce**
Use @sentry/react to generate data which includes a session item in an envelope request

**Expected behavior**
Session, and other types of items other than transactions, do not cause an error

**Sentry Versions (please complete the following information):**
 - Sentry: @sentry/react @ 6.11.0
 - Sentry-Testkit 3.3.4

**Comment by kenkku** [comment]
I just had a look at the history for this code and looks like it was introduced in #82 and I was able to work around this issue by downgrading to sentry-testkit 3.3.2
